name: ToyGl
channels:
  - conda-forge/label/cf202003
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24.3
  - scipy>=1.10.1
  - natsort>=7.1.1
  - pyvista>=0.37.0
  - dill>=0.3.7
  - pip
  - pip:
      # Any additional pip dependencies